services:
  concert:
    build: .
    container_name: concert1
    user: root          # ← add this
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    command: npm run dev
    networks:
      - local-network